# Snakemake configuration file

# Specify paths to data files
#
# Paths must end with forward slash
dir_proj: /project2/gilad/jdblischak/cardioqtl/
scratch: /scratch/midway2/jdblischak/
# Make sure to also update path for log files in cluster.json
dir_log: log/

# Specify Ensembl release for genome sequence and annotation
# http://feb2014.archive.ensembl.org/index.html
ensembl_archive: feb2014.archive.ensembl.org
ensembl_rel: 75
ensembl_genome: GRCh37.75

# Specify cis-window around TSS for testing eQTLs (TSS +/- window)
window: 1000000

# Specify chromosomes
#
# For quantifying gene expression
chr_genes: ["1", "2", "3", "4", "5", "6", "7", "8", "9",
            "10", "11", "12", "13", "14", "15", "16",
            "17", "18", "19", "20", "21", "22",
            "X", "Y", "MT"]
# For mapping eQTLs
chr_snps: ["1", "2", "3", "4", "5", "6", "7", "8", "9",
           "10", "11", "12", "13", "14", "15", "16",
           "17", "18", "19", "20", "21", "22"]

# Specify number of PCs to regress
n_pcs: 10

# GWAS on phenotypes
phenos: ["bri", "chi", "cho", "cim", "dbp", "eno", "eos",
         "fev", "fvc", "hdl", "ige", "lav", "ldl", "lvm",
         "lym", "mon", "neu", "sbp", "tri", "ykl"]
