# Conda configuration file to reproduce computing environment
#
# Create the conda environment:
# conda env create -n cardioqtl --file environment.yaml
#
# Activate the conda environment:
# source activate cardioqtl
#
# Deactivate the conda environmnet:
# source deactivate cardioqtl
#
# https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand
# https://bioconda.github.io

name: cardioqtl
channels:
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - bioconductor-biomart=2.28.0
  - bioconductor-edger=3.16.5
  - plink2=1.90b3.35
  - python=3.5.2
  - r=3.3.1
  - r-dplyr=0.5.0
  - r-magrittr=1.5
  - r-stringr=1.1.0
  - rpy2=2.8.5
  - samtools=1.3.1
  - snakemake=3.11.2
  - subread=1.5.0.post3
  - verifybamid=1.1.3
