# Conda configuration file to reproduce computing environment
#
# Create the conda environment:
# conda env create -n cardioqtl --file environment.yaml
#
# Activate the conda environment:
# source activate cardioqtl
#
# Deactivate the conda environmnet:
# source deactivate cardioqtl
#
# https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html
# https://conda.io/docs/using/envs.html#create-environment-file-by-hand
# https://bioconda.github.io
# https://anaconda.org/MarcosRodrigues/r-cowplot/files

name: cardioqtl
channels:
  - bioconda
  - r
  - defaults
  - marcosrodrigues
  - conda-forge
dependencies:
  - bioconductor-biomart=2.28.0
  - bioconductor-edger=3.16.5
  - bioconductor-genomicranges=1.26.4
  - bioconductor-rtracklayer=1.34.2
  - plink2=1.90b3.35
  - python=3.5.2
  - r=3.3.1
  - r-cowplot=0.7.0
  - r-rcolorbrewer=1.1_2
  - r-dplyr=0.5.0
  - r-ggplot2=2.2.1
  - r-git2r=0.15.0
  - r-hmisc=3.17_4
  - r-knitr=1.12.3
  - r-magrittr=1.5
  - r-plyr=1.8.4
  - r-qqman=0.1.2
  - r-readr=0.2.2
  - r-rmarkdown=0.9.5
  - r-stringr=1.1.0
  - r-tidyr=0.6.0
  - rpy2=2.8.5
  - samtools=1.3.1
  - snakemake=3.11.2
  - subread=1.5.0.post3
  - verifybamid=1.1.3
